### ISSUE TITLE
Add Howitt et al 

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/TeamCOMPAS.github.io#14]
Title : Luminous Red Novae: population models and future prospects

Authors: George Howitt, Simon Stevenson, Alejandro Vigna-Gómez, Stephen Justham, Natasha Ivanova, Tyrone E. Woods, Coenraad J. Neijssel, Ilya Mandel
arXiv: https://arxiv.org/abs/1912.07771
Journal : Monthly Notices of the Royal Astronomical Society

Abstract
A class of optical transients known as Luminous Red Novae (LRNe) have recently been associated with mass ejections from binary stars undergoing common-envelope evolution. We use the population synthesis code COMPAS to explore the impact of a range of assumptions about the physics of common-envelope evolution on the properties of LRNe. In particular, we investigate the influence of various models for the energetics of LRNe on the expected event rate and light curve characteristics, and compare with the existing sample. We find that the Galactic rate of LRNe is ∼0.2 yr−1, in agreement with the observed rate. In our models, the luminosity function of Galactic LRNe covers multiple decades in luminosity and is dominated by signals from stellar mergers, consistent with observational constraints from iPTF and the Galactic sample of LRNe. We discuss how observations of the brightest LRNe may provide indirect evidence for the existence of massive (>40 M⊙) red supergiants. Such LRNe could be markers along the evolutionary pathway leading to the formation of double compact objects. We make predictions for the population of LRNe observable in future transient surveys with the Large Synoptic Survey Telescope and the Zwicky Transient Facility. In all plausible circumstances, we predict a selection-limited observable population dominated by bright, long-duration events caused by common envelope ejections. We show that the Large Synoptic Survey Telescope will observe 20--750 LRNe per year, quickly constraining the luminosity function of LRNe and probing the physics of common-envelope events. 

![plateau_optimistic_CE](https://user-images.githubusercontent.com/6952112/74893361-4c884480-53e0-11ea-8a36-12919c161542.png)

**Comment by ilyamandel** [comment]
Added and closed.
