### ISSUE TITLE
Add Chattopadhyay et al 

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/TeamCOMPAS.github.io#15]
Modelling Double Neutron Stars: Radio and Gravitational Waves
Debatri Chattopadhyay, Simon Stevenson, Jarrod R. Hurley, Luca J. Rossi, Chris Flynn
arXiv:https://arxiv.org/abs/1912.02415

We have implemented prescriptions for modelling pulsars in the rapid binary population synthesis code COMPAS. We perform a detailed analysis of the double neutron star (DNS) population, accounting for radio survey selection effects. The surface magnetic field decay timescale (≈1000\,Myr) and mass scale (≈0.02\,M⊙) are the dominant uncertainties in our model. Mass accretion during common envelope evolution plays a non-trivial role in recycling pulsars. We find a best-fit model that is in broad agreement with the observed Galactic DNS population. Though the pulsar parameters (period and period derivative) are strongly biased by radio selection effects, the observed orbital parameters (orbital period and eccentricity) closely represent the intrinsic distributions. The number of radio observable DNSs in the Milky Way at present is ≈\,2500 in our model, only ≈\,10\% of the predicted total number of DNSs in the galaxy. Using our model calibrated to the Galactic DNS population, we make predictions for DNS mergers observed in gravitational waves. The DNS chirp mass distribution varies from ≈1.1M⊙ to ≈2.1M⊙ and median is obtained to be 1.14\,M⊙. The expected effective spin χeff for isolated DNSs is ≲0.03 from our model. We predict that ≈34\% of the current Galactic isolated DNSs will merge within a Hubble time, and have a median total mass of 2.7\,M⊙. Finally, we discuss implications for fast radio bursts and post-merger remnant gravitational-waves.

**Comment by SimonStevenson** [comment]
Now accepted in MNRAS

**Comment by ilyamandel** [comment]
Added, issue closed.
