### ISSUE TITLE
Add Vigna-Gomez et al 2020

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/TeamCOMPAS.github.io#16]
Common-Envelope Episodes that lead to Double Neutron Star formation
Alejandro Vigna-Gómez, Morgan MacLeod, Coenraad J. Neijssel, Floor S. Broekgaarden, Stephen Justham, George Howitt, Selma E. de Mink, Ilya Mandel

arXiv: https://arxiv.org/abs/2001.09829

Close Double Neutron Stars (DNSs) have been observed as Galactic radio pulsars, while their mergers have been detected as gamma-ray bursts and gravitational-wave sources. They are believed to have experienced at least one common-envelope episode (CEE) during their evolution prior to DNS formation. In the last decades there have been numerous efforts to understand the details of the common-envelope phase, but its computational modelling remains challenging. We present and discuss the properties of the donor and the binary at the onset of the Roche-lobe overflow (RLOF) leading to these CEEs as predicted by rapid binary population synthesis models. These properties can be used as initial conditions for detailed simulations of the common-envelope phase. There are three distinctive populations, classified by the evolutionary stage of the donor at the moment of the onset of the RLOF: giant donors with fully-convective envelopes, cool donors with partially-convective envelopes, and hot donors with radiative envelopes. We also estimate that, for standard assumptions, tides would not circularise a large fraction of these systems by the onset of RLOF. This makes the study and understanding of eccentric mass transferring systems relevant for DNS populations.

**Comment by ilyamandel** [comment]
Added, issue closed.
