### ISSUE TITLE
Paper master list

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/TeamCOMPAS.github.io#17]
The old ADS master list from Christopher is out of date.  We may wish to create our own at some point; for now, I've just omitted it (effectively, the list is on the COMPAS science page, anyway).

**Comment by SimonStevenson** [comment]
https://ui.adsabs.harvard.edu/public-libraries/gzRk1qpbRUy4cP2GydR36Q

**Comment by ilyamandel** [comment]
Oh, I already updated that link right after I created the library, just forgot to close the issue. :)  Thanks for the reminder -- closing now.
