### ISSUE TITLE
Update email address

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/TeamCOMPAS.github.io#18]
The email icon on the compas.science homepage still uses compas@star.sr.bham.ac.uk as the email address. We should probably update this to our current contact details (compas-user@googlegroups.com , I think? )

**Comment by ilyamandel** [comment]
Fixed this, and also updated the old repo GitHub pointer to the new one while I was at it.  Thanks for spotting this, Simon!
