### ISSUE TITLE
Add Chattopadhyay et al. to recently posted papers

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/TeamCOMPAS.github.io#22]
Add Chattopadhyay et al. to recently posted papers

arXiv:
https://arxiv.org/abs/2011.13503

Title
Modelling Neutron Star-Black Hole Binaries: Future Pulsar Surveys and Gravitational Wave Detectors

Authors
Debatri Chattopadhyay, Simon Stevenson, Jarrod R. Hurley, Matthew Bailes, Floor Broekgaarden

Abstract
Binaries comprised of a neutron star (NS) and a black hole (BH) have so far eluded observations as pulsars and with gravitational waves (GWs). We model the formation and evolution of these NS+BH binaries including pulsar evolution using the binary population synthesis code COMPAS. We predict the presence of a total of 50-1300 binaries containing a pulsar and a BH (PSR+BHs) in the Galactic field. We find the population observable by the next-generation of radio telescopes, represented by the SKA and MeerKAT, current (LIGO/Virgo) and future (LISA) GW detectors. We conclude that the SKA will observe 1-60 PSR+BHs, with 0-4 binaries containing millisecond pulsars. MeerKAT is expected to observe 0-30 PSR+BH systems. Future radio detections of NS+BHs will constrain uncertain binary evolution processes such as BH natal kicks. We show that systems in which the NS formed first (NSBH) can be distinguished from those where the BH formed first (BHNS) by their pulsar and binary properties. We find 40% of the LIGO/Virgo observed NS+BHs from a Milky-Way like field population will have a chirp mass ≥3.0 M⊙. We estimate the spin distributions of NS+BHs with two models for the spins of BHs. The remnants of BHNS mergers will have a spin of ∼0.4, whilst NSBH merger remnants can have a spin of ∼0.6 or ∼0.9 depending on the model for BH spins. We estimate that approximately 25-930 PSR+BHs will be radio alive whilst emitting GWs in the LISA frequency band, raising the possibility of joint observation by the SKA and LISA. 

[observed_PPdot_SKA.pdf](https://github.com/TeamCOMPAS/TeamCOMPAS.github.io/files/5640230/observed_PPdot_SKA.pdf)
[Observed_flux_vs_spin_period.pdf](https://github.com/TeamCOMPAS/TeamCOMPAS.github.io/files/5640231/Observed_flux_vs_spin_period.pdf)

Figures 1 & 2 attached

**Comment by reinhold-willcox** [comment]
All pushed up (we're not using PRs for the website, so please double check that the public page looks correct).

**Comment by ilyamandel** [comment]
Added to ADS library.  @reinhold-willcox -- thanks, you didn't add it to the news menu bar, but I can do that in a second.

**Comment by ilyamandel** [comment]
Done, closing.

**Comment by SimonStevenson** [comment]
Thanks both!
