### ISSUE TITLE
Add papers to website

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/TeamCOMPAS.github.io#26]
Two Cyg X-1 papers and Floor's latest

**Comment by ilyamandel** [comment]
See links in library: https://ui.adsabs.harvard.edu/user/libraries/gzRk1qpbRUy4cP2GydR36Q

**Comment by reinhold-willcox** [comment]
Done

**Comment by ilyamandel** [comment]
@reinhold-willcox : looks like the Miller-Jones+ paper has an incorrectly copied title .  Also, when you get a chance, could you please add these to the news tracker on the right, so it doesn't look like we have no recent news?  (A single item for the two Cyg X-1 papers is probably enough, and a separate one for Floor's paper.)

**Comment by reinhold-willcox** [comment]
Haven't checked GitHub in a while, just seeing this now.

Yup, on it

**Comment by ilyamandel** [comment]
Thank you for the fix, @reinhold-willcox -- closing.
