### ISSUE TITLE
Add paper

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/TeamCOMPAS.github.io#27]
https://arxiv.org/abs/2106.01552

to website (@reinhold-willcox ?)

and to COMPAS ADS library (@ilyamandel )

**Comment by reinhold-willcox** [comment]
added to website

**Comment by ilyamandel** [comment]
Thanks, @reinhold-willcox !  This one you got on the main page but not the side-scroller, unlike the previous ones, which ended up on the side-scroller but not the main page. :) 
Maybe we can somehow automate the process so there's only one place where things need to be added.  Hmm...

**Comment by reinhold-willcox** [comment]
Woops! I'll fix that.

Yes, I agree on automating this. It would be nice to just have a list of arxiv links, and some parsing script to put the rest of it together.

**Comment by reinhold-willcox** [comment]
Added to news, let me know if the description I wrote looks good.

**Comment by ilyamandel** [comment]
Looks good, thanks!
