### ISSUE TITLE
Add Willcox+

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/TeamCOMPAS.github.io#28]
https://ui.adsabs.harvard.edu/abs/2021arXiv210704251W/ should be added to COMPAS publications on web page (already added to ADS).

**Comment by reinhold-willcox** [comment]
@ilyamandel On it now. But I noticed the NASA/ADS page shows "No sources found", even though the arxiv link is correct lower down the page. How do I update the sources list?

**Comment by reinhold-willcox** [comment]
^ I'll ping you on slack about this so I can close the issue
