### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/TeamCOMPAS.github.io#30]
New feature idea: automatically add paper (and News notification) for new papers based on an arxiv or adsabs link.

**Comment by reinhold-willcox** [comment]
@ilyamandel Tagging you since I think you and I are the only ones that use this repo. 

The tedium of adding in new papers was starting to get to me, so I've written a script to do it automatically. `new_paper_parser.py` runs without arguments, but it will ask for the url (either arxiv or ads), and a synopsis for the news column, then it updates science.html. It was tested on a few different cases, but not rigorously, so we should make sure to vet the website changes locally before pushing.

**Comment by ilyamandel** [comment]
Very nicely done, @reinhold-willcox !!!
