### ISSUE TITLE
Add Debatri's new paper

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/TeamCOMPAS.github.io#33]
https://ui.adsabs.harvard.edu/abs/2022arXiv220305850C/abstract?utm_source=myads&utm_medium=email&utm_campaign=type:arxiv&utm_term=8530&utm_content=rank:14

**Comment by ilyamandel** [comment]
Added to COMPAS ADS library.

**Comment by SimonStevenson** [comment]
Thanks both!

**Comment by reinhold-willcox** [comment]
added to compas website

**Comment by reinhold-willcox** [comment]
Nevermind, I broke something in my repo, reopening until I can get it fixed.

**Comment by reinhold-willcox** [comment]
now done, parser is fixed
