### ISSUE TITLE
Add Chattopadhyay 2022b?

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/TeamCOMPAS.github.io#35]
https://ui.adsabs.harvard.edu/abs/2022MNRAS.tmp.1136C/abstract

It's not strictly a COMPAS paper, but it has many compas people (and discusses using it as a future improvement). @ilyamandel What do you think?

**Comment by reinhold-willcox** [comment]
@ilyamandel ping

**Comment by ilyamandel** [comment]
Sorry, @reinhold-willcox .

I think we should stick to papers that use COMPAS for this website.  This is an interesting paper, but probably not necessary here.  I'll close the issue.
